# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.schema.model.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class RiskMining:
    
    class App(SPGTypeHelper):
        
    
        useCert = PropertyHelper("useCert")
        belongTo = PropertyHelper("belongTo")
        riskMark = PropertyHelper("riskMark")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
    
    
    
    class Cert(SPGTypeHelper):
        
    
        id = PropertyHelper("id")
        certNum = PropertyHelper("certNum")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
    
    
    
    class Company(SPGTypeHelper):
        
    
        id = PropertyHelper("id")
        hasPhone = PropertyHelper("hasPhone")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
    
        holdShare = RelationHelper("holdShare")
        hasCert = RelationHelper("hasCert")
    
    
    class Device(SPGTypeHelper):
        
    
        umid = PropertyHelper("umid")
        install = PropertyHelper("install")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
    
    
    
    class Person(SPGTypeHelper):
        
        class fundTrans(RelationHelper):
            transAmt = PropertyHelper("transAmt")
            transDate = PropertyHelper("transDate")
    
        hasPhone = PropertyHelper("hasPhone")
        belongTo = PropertyHelper("belongTo")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        age = PropertyHelper("age")
    
        holdShare = RelationHelper("holdShare")
        release = RelationHelper("release")
        hasDevice = RelationHelper("hasDevice")
        developed = RelationHelper("developed")
        hasCert = RelationHelper("hasCert")
    
        fundTrans = fundTrans("fundTrans")
    
    class TaxOfRiskApp(SPGTypeHelper):
        
    
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
    
    
    
    class TaxOfRiskUser(SPGTypeHelper):
        
    
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
    
    
    
    App = App("RiskMining.App")
    Cert = Cert("RiskMining.Cert")
    Company = Company("RiskMining.Company")
    Device = Device("RiskMining.Device")
    Person = Person("RiskMining.Person")
    TaxOfRiskApp = TaxOfRiskApp("RiskMining.TaxOfRiskApp")
    TaxOfRiskUser = TaxOfRiskUser("RiskMining.TaxOfRiskUser")
    
    pass