# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.schema.model.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class MovieMining:
    
    class Genre(SPGTypeHelper):
        
    
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        description = PropertyHelper("description")
    
    
    
    class Movie(SPGTypeHelper):
        
    
        rating = PropertyHelper("rating")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        introduction = PropertyHelper("introduction")
        releaseDate = PropertyHelper("releaseDate")
        description = PropertyHelper("description")
    
        hasGenre = RelationHelper("hasGenre")
    
    
    class Person(SPGTypeHelper):
        
    
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        deathDate = PropertyHelper("deathDate")
        birthDate = PropertyHelper("birthDate")
        birthPlace = PropertyHelper("birthPlace")
        biography = PropertyHelper("biography")
        description = PropertyHelper("description")
    
        actIn = RelationHelper("actIn")
    
    
    Genre = Genre("MovieMining.Genre")
    Movie = Movie("MovieMining.Movie")
    Person = Person("MovieMining.Person")
    
    pass