# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.schema.model.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class SupplyChain:
    
    class Company(SPGTypeHelper):
        
        class fundTrans(RelationHelper):
            transDate = PropertyHelper("transDate")
            transAmt = PropertyHelper("transAmt")
    
        fundTrans6Month = PropertyHelper("fundTrans6Month")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        cashflowDiff1Month = PropertyHelper("cashflowDiff1Month")
        id = PropertyHelper("id")
        cashflowDiff6Month = PropertyHelper("cashflowDiff6Month")
        fundTrans1Month = PropertyHelper("fundTrans1Month")
        cashflowDiff3Month = PropertyHelper("cashflowDiff3Month")
        fundTrans3MonthIn = PropertyHelper("fundTrans3MonthIn")
        totalTransInAmt = PropertyHelper("totalTransInAmt")
        fundTrans3Month = PropertyHelper("fundTrans3Month")
        fundTrans1MonthIn = PropertyHelper("fundTrans1MonthIn")
        fundTrans6MonthIn = PropertyHelper("fundTrans6MonthIn")
        product = PropertyHelper("product")
    
        belongToIndustry = RelationHelper("belongToIndustry")
        sameLegalRepresentative = RelationHelper("sameLegalRepresentative")
        mainSupply = RelationHelper("mainSupply")
    
        fundTrans = fundTrans("fundTrans")
    
    class CompanyEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        leadTo = PropertyHelper("leadTo")
        subject = PropertyHelper("subject")
        index = PropertyHelper("index")
        eventTime = PropertyHelper("eventTime")
        trend = PropertyHelper("trend")
        belongTo = PropertyHelper("belongTo")
    
    
    
    class Index(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    
    
    class Industry(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    
    
    class Person(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        certNo = PropertyHelper("certNo")
        age = PropertyHelper("age")
        legalRepresentative = PropertyHelper("legalRepresentative")
    
    
    
    class Product(SPGTypeHelper):
        
    
        hasSupplyChain = PropertyHelper("hasSupplyChain")
        belongToIndustry = PropertyHelper("belongToIndustry")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        belongTo = PropertyHelper("belongTo")
    
    
    
    class ProductChainEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        subject = PropertyHelper("subject")
        index = PropertyHelper("index")
        eventTime = PropertyHelper("eventTime")
        trend = PropertyHelper("trend")
        belongTo = PropertyHelper("belongTo")
    
        leadTo = RelationHelper("leadTo")
    
    
    class TaxOfCompanyEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    
    
    class TaxOfProdEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
        leadTo = RelationHelper("leadTo")
    
    
    class TaxOfProduct(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    
    
    class Trend(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    
    
    Company = Company("SupplyChain.Company")
    CompanyEvent = CompanyEvent("SupplyChain.CompanyEvent")
    Index = Index("SupplyChain.Index")
    Industry = Industry("SupplyChain.Industry")
    Person = Person("SupplyChain.Person")
    Product = Product("SupplyChain.Product")
    ProductChainEvent = ProductChainEvent("SupplyChain.ProductChainEvent")
    TaxOfCompanyEvent = TaxOfCompanyEvent("SupplyChain.TaxOfCompanyEvent")
    TaxOfProdEvent = TaxOfProdEvent("SupplyChain.TaxOfProdEvent")
    TaxOfProduct = TaxOfProduct("SupplyChain.TaxOfProduct")
    Trend = Trend("SupplyChain.Trend")
    
    pass